"""add status to grade students

Revision ID: 0a060dd45acd
Revises: b5e335c0ba4d
Create Date: 2025-10-18 16:54:57.366717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a060dd45acd'
down_revision: Union[str, Sequence[str], None] = 'b5e335c0ba4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('grade', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'grade')
    # ### end Alembic commands ###
