"""update new colmuns in table catechist

Revision ID: 0b588b774642
Revises: afbef9f054a8
Create Date: 2026-01-21 21:55:10.884475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b588b774642'
down_revision: Union[str, Sequence[str], None] = 'afbef9f054a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catechists', sa.Column('ci', sa.String(length=50), nullable=True))
    op.add_column('catechists', sa.Column('service_years', sa.String(length=50), nullable=True))
    op.create_unique_constraint('uq_catechists_ci', 'catechists', ['ci'])

    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_catechists_ci', 'catechists', type_='unique')
    op.drop_column('catechists', 'service_years')
    op.drop_column('catechists', 'ci')
    # ### end Alembic commands ###
