"""add photo  to grade students

Revision ID: 213f1c09dee9
Revises: 623687bdcef1
Create Date: 2025-10-23 11:21:37.440257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213f1c09dee9'
down_revision: Union[str, Sequence[str], None] = '623687bdcef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sacraments_student_id_key'), 'sacraments', type_='unique')
    op.drop_constraint(op.f('sacraments_student_id_fkey'), 'sacraments', type_='foreignkey')
    op.create_foreign_key(None, 'sacraments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('students', sa.Column('photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'photo_url')
    op.drop_constraint(None, 'sacraments', type_='foreignkey')
    op.create_foreign_key(op.f('sacraments_student_id_fkey'), 'sacraments', 'students', ['student_id'], ['id'])
    op.create_unique_constraint(op.f('sacraments_student_id_key'), 'sacraments', ['student_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
