"""add catechists

Revision ID: 3081154a4e04
Revises: 62a393c5abbc
Create Date: 2025-11-14 22:49:29.993758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3081154a4e04'
down_revision: Union[str, Sequence[str], None] = '62a393c5abbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catechists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('COORDINATOR', 'CATECHIST', 'ASSISTANT', 'SECRETARY', name='catechistrole'), nullable=False),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('scheduled', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RETIRED', name='catechiststatus'), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('catechist_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catechist_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catechist_attendance')
    op.drop_table('catechists')
    # ### end Alembic commands ###
