"""Fix catechist_attendance types

Revision ID: 75f5cf0719b4
Revises: d053705ce1ca
Create Date: 2025-11-15 17:59:16.472291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f5cf0719b4'
down_revision: Union[str, Sequence[str], None] = 'd053705ce1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catechist_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catechist_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('presente', 'ausente', 'justificado', 'tarde', name='attendancestatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catechist_attendance')
    # ### end Alembic commands ###
