"""add user_id to catechists

Revision ID: 8fa62458944d
Revises: c8ffed717643
Create Date: 2026-02-26 22:01:36.551481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fa62458944d'
down_revision: Union[str, Sequence[str], None] = 'c8ffed717643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catechists', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'catechists', ['user_id'])
    op.create_foreign_key(None, 'catechists', 'users', ['user_id'], ['id'])
    op.add_column('students', sa.Column('catechist_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'students', 'catechists', ['catechist_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'parroco', 'catequista', 'secretario', 'auxiliar', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'parroco', 'catequista', 'secretario', 'auxiliar', name='userrole'),
               nullable=True)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'catechist_id')
    op.drop_constraint(None, 'catechists', type_='foreignkey')
    op.drop_constraint(None, 'catechists', type_='unique')
    op.drop_column('catechists', 'user_id')
    # ### end Alembic commands ###
