"""Fix students_attendance types

Revision ID: af64b33ceada
Revises: 75f5cf0719b4
Create Date: 2025-11-16 13:14:21.661510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af64b33ceada'
down_revision: Union[str, Sequence[str], None] = '75f5cf0719b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'catechist_attendance', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catechist_attendance', type_='unique')
    # ### end Alembic commands ###
