"""update user_id to catechists

Revision ID: b220770671b2
Revises: 8fa62458944d
Create Date: 2026-02-26 22:29:16.831332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b220770671b2'
down_revision: Union[str, Sequence[str], None] = '8fa62458944d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catechist_student',
    sa.Column('catechist_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('catechist_id', 'student_id')
    )
    op.alter_column('catechists', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('students', 'catechist_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'catechist_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('catechists', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('catechist_student')
    # ### end Alembic commands ###
