"""add status to students

Revision ID: b5e335c0ba4d
Revises: d9664e82a952
Create Date: 2025-10-18 12:12:07.280119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e335c0ba4d'
down_revision: Union[str, Sequence[str], None] = 'd9664e82a952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum('active', 'inactive', name='studentstatus')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('students', sa.Column('status', status_enum, nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'status')
    status_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
