"""add catechists

Revision ID: bdd9fede2331
Revises: 3081154a4e04
Create Date: 2025-11-15 15:34:41.012425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd9fede2331'
down_revision: Union[str, Sequence[str], None] = '3081154a4e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'catechist_attendance', ['id'])
    op.create_unique_constraint(None, 'catechists', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catechists', type_='unique')
    op.drop_constraint(None, 'catechist_attendance', type_='unique')
    # ### end Alembic commands ###
