"""add grupos catequesis

Revision ID: d9507a490c46
Revises: b220770671b2
Create Date: 2026-02-27 23:42:49.504366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9507a490c46'
down_revision: Union[str, Sequence[str], None] = 'b220770671b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grup_catechistis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grup_catechist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grup_id', sa.UUID(), nullable=False),
    sa.Column('catechist_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], ),
    sa.ForeignKeyConstraint(['grup_id'], ['grup_catechistis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('catechist_student')
    
    op.alter_column('catechists', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('students', sa.Column('grup_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('students_catechist_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'grup_catechistis', ['grup_id'], ['id'])
    op.drop_column('students', 'catechist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('catechist_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_catechist_id_fkey'), 'students', 'catechists', ['catechist_id'], ['id'])
    op.drop_column('students', 'grup_id')
    op.alter_column('catechists', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('catechist_student',
    sa.Column('catechist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['catechist_id'], ['catechists.id'], name=op.f('catechist_student_catechist_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('catechist_student_student_id_fkey')),
    sa.PrimaryKeyConstraint('catechist_id', 'student_id', name=op.f('catechist_student_pkey'))
    )
    op.drop_table('grup_catechist')
    op.drop_table('grup_catechistis')
    # ### end Alembic commands ###
