"""add sacrament dates

Revision ID: d9664e82a952
Revises: 2c41ea1bd7b3
Create Date: 2025-10-18 11:00:53.348861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9664e82a952'
down_revision: Union[str, Sequence[str], None] = '2c41ea1bd7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notes', ['id'])
    op.create_unique_constraint(None, 'parents', ['id'])
    op.add_column('sacraments', sa.Column('baptism_date', sa.Date(), nullable=True))
    op.add_column('sacraments', sa.Column('first_communion_date', sa.Date(), nullable=True))
    op.add_column('sacraments', sa.Column('confirmation_date', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'sacraments', ['id'])
    op.drop_constraint(op.f('sacraments_student_id_fkey'), 'sacraments', type_='foreignkey')
    op.create_foreign_key(None, 'sacraments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sacraments', 'date')
    op.drop_column('sacraments', 'type')
    op.create_unique_constraint(None, 'students', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.add_column('sacraments', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('sacraments', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sacraments', type_='foreignkey')
    op.create_foreign_key(op.f('sacraments_student_id_fkey'), 'sacraments', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'sacraments', type_='unique')
    op.drop_column('sacraments', 'confirmation_date')
    op.drop_column('sacraments', 'first_communion_date')
    op.drop_column('sacraments', 'baptism_date')
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_constraint(None, 'notes', type_='unique')
    # ### end Alembic commands ###
