"""add status to grade students

Revision ID: fcaa88d5dd57
Revises: 0a060dd45acd
Create Date: 2025-10-18 21:13:48.590261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaa88d5dd57'
down_revision: Union[str, Sequence[str], None] = '0a060dd45acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sacraments', ['student_id'])
    op.drop_constraint(op.f('sacraments_student_id_fkey'), 'sacraments', type_='foreignkey')
    op.create_foreign_key(None, 'sacraments', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sacraments', type_='foreignkey')
    op.create_foreign_key(op.f('sacraments_student_id_fkey'), 'sacraments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sacraments', type_='unique')
    # ### end Alembic commands ###
